version: '3'
networks:
  dem: 
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dsubhlok
      POSTGRES_PASSWORD: dsubhlok
      POSTGRES_DB: go_student
    ports:
      - 5432:5432
    networks:
      - dem
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks:
      - dem
