name: CI/CD Pipeline for DBT and Python Scripts

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Optionally triggers on PRs to main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  test-dbt:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install DBT and dependencies
        run: |
          pip install dbt
          # Add any other dependencies here
          dbt deps

      - name: Run DBT Tests
        env:
          DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES_DIR }}
          DBT_CONNECTION_STRING: ${{ secrets.DBT_CONNECTION_STRING }}
        run: |
          dbt seed --profiles-dir $DBT_PROFILES_DIR  # Load seed data if needed
          dbt run --models +model_name  # Run specific models
          dbt test --models +model_name  # Run tests on models

  test-python:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust if using Pipenv or Poetry

      - name: Run Python tests
        run: |
          pytest tests/  # Run your Python tests, specify the tests directory if necessary

  deploy-dbt:
    runs-on: ubuntu-latest
    needs: [test-dbt, test-python]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install DBT and dependencies
        run: |
          pip install dbt
          dbt deps

      - name: Deploy DBT Models
        env:
          DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES_DIR }}
          DBT_CONNECTION_STRING: ${{ secrets.DBT_CONNECTION_STRING }}
        run: |
          dbt run --models +model_name
          dbt test --models +model_name
